# Generated by Django 3.1.4 on 2021-02-03 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elearningapp', '0039_auto_20210203_1027'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email_address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSpecificProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_score', models.IntegerField(default=0)),
                ('number_of_tests_taken', models.PositiveIntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('lowest_score', models.IntegerField(default=0)),
                ('average_score', models.IntegerField(default=0)),
                ('admin_of', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of', to='elearningapp.course')),
                ('collaborator_of', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborator_of', to='elearningapp.course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
