# Generated by Django 3.1.7 on 2021-03-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursespecificprofile',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_course_specific_profile'),
        ),
    ]
