# Generated by Django 3.1.4 on 2021-02-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0039_auto_20210203_1027'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursespecificprofile',
            name='admin_of',
        ),
        migrations.RemoveField(
            model_name='coursespecificprofile',
            name='collaborator_of',
        ),
        migrations.RemoveField(
            model_name='globalprofile',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='globalprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='globalprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='globalprofile',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of_course', to='elearningapp.course'),
        ),
        migrations.AddField(
            model_name='globalprofile',
            name='contributes_to',
            field=models.ManyToManyField(to='elearningapp.Course'),
        ),
        migrations.AddField(
            model_name='globalprofile',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
