# Generated by Django 3.1.4 on 2021-02-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0040_auto_20210203_1213'),
        ('users', '0002_auto_20210203_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalprofile',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of_course', to='elearningapp.course'),
        ),
        migrations.AlterField(
            model_name='globalprofile',
            name='contributes_to',
            field=models.ManyToManyField(blank=True, to='elearningapp.Course'),
        ),
    ]
