# Generated by Django 3.1.4 on 2021-02-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210203_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursespecificprofile',
            name='average_score',
        ),
    ]
