# Generated by Django 3.1.4 on 2021-02-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_coursespecificprofile_average_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalprofile',
            old_name='admin',
            new_name='admin_of',
        ),
        migrations.RemoveField(
            model_name='globalprofile',
            name='contributes_to',
        ),
    ]
