# Generated by Django 3.1.4 on 2021-02-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0045_auto_20210207_1346'),
        ('users', '0005_auto_20210207_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalprofile',
            name='admin_of',
        ),
        migrations.AddField(
            model_name='globalprofile',
            name='admin_of',
            field=models.ManyToManyField(related_name='admin_of_course', to='elearningapp.Course'),
        ),
    ]
