# Generated by Django 3.1.6 on 2021-02-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0046_auto_20210207_2133'),
        ('users', '0006_auto_20210207_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalprofile',
            name='admin_of',
            field=models.ManyToManyField(blank=True, related_name='admin_of_course', to='elearningapp.Course'),
        ),
    ]
