# Generated by Django 3.1.1 on 2020-11-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_questions_per_test', models.IntegerField(default=10)),
                ('category_distribution', models.JSONField()),
            ],
        ),
    ]
