# Generated by Django 3.1.1 on 2020-11-29 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elearningapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='answers_per_question',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='points_for_correct_answer',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='points_for_unanswered',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='points_for_wrong_answer',
            field=models.FloatField(default=-0.5),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('correct_answer_index', models.IntegerField()),
                ('solution_text', models.CharField(max_length=3000)),
                ('hint_text', models.CharField(max_length=1000, null=True)),
                ('edits_history', models.JSONField()),
                ('number_of_appearences', models.IntegerField(default=0)),
                ('number_of_selections_per_answer', models.JSONField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSpecificProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_score', models.IntegerField()),
                ('number_of_tests_taken', models.IntegerField()),
                ('highest_score', models.IntegerField()),
                ('lowest_score', models.IntegerField()),
                ('average_score', models.IntegerField()),
                ('admin_of', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of', to='elearningapp.course')),
                ('collaborator_of', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborator_of', to='elearningapp.course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('answer_index', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.question')),
            ],
        ),
    ]
