# Generated by Django 3.1.1 on 2020-11-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0002_auto_20201129_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='minimum_passing_score',
            field=models.FloatField(default=5),
        ),
    ]
