# Generated by Django 3.1.1 on 2020-11-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0004_activequestion_activetest_answersintakentest_seenquestion_takentest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
