# Generated by Django 3.1.1 on 2020-11-29 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0005_course_setup_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='course',
        ),
    ]
