# Generated by Django 3.1.1 on 2020-11-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0006_auto_20201129_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category_distribution',
            field=models.JSONField(blank=True),
        ),
    ]
