# Generated by Django 3.1.1 on 2020-11-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0007_auto_20201129_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursespecificprofile',
            name='average_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursespecificprofile',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursespecificprofile',
            name='last_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursespecificprofile',
            name='lowest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursespecificprofile',
            name='number_of_tests_taken',
            field=models.IntegerField(default=0),
        ),
    ]
