# Generated by Django 3.1.1 on 2020-11-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0008_auto_20201129_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='edits_history',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='number_of_selections_per_answer',
            field=models.JSONField(blank=True),
        ),
    ]
