# Generated by Django 3.1.1 on 2020-12-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0012_takentest_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='takentest',
            name='taken_test',
            field=models.IntegerField(default=0),
        ),
    ]
