# Generated by Django 3.1.1 on 2020-12-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0013_takentest_taken_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takentest',
            old_name='taken_test',
            new_name='passing',
        ),
    ]
