# Generated by Django 3.1.1 on 2020-12-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0014_auto_20201202_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='globalprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
