# Generated by Django 3.1.4 on 2020-12-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0015_auto_20201202_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('minimum_passing_testcase_perc', models.IntegerField(default=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_case', models.TextField()),
                ('expected_output', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.programexercise')),
            ],
        ),
    ]
