# Generated by Django 3.1.4 on 2020-12-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0016_programexercise_testcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programexercise',
            old_name='visible',
            new_name='is_visible',
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
