# Generated by Django 3.1.4 on 2020-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0017_auto_20201210_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exercise_modality',
            field=models.CharField(choices=[('SQ', 'Domande singole'), ('MQ', 'Domande raggruppate'), ('JS', 'Esercizi JavaScript')], default='SQ', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(default='IT', max_length=2, null=True),
        ),
    ]
