# Generated by Django 3.1.4 on 2021-02-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0020_auto_20210131_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text_source',
            new_name='source_text',
        ),
    ]
