# Generated by Django 3.1.4 on 2021-02-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0021_auto_20210201_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='rendered_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='rendered_text',
        ),
    ]
