# Generated by Django 3.1.4 on 2021-02-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0022_auto_20210201_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='source_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='source_text',
            new_name='text',
        ),
    ]
