# Generated by Django 3.1.4 on 2021-02-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0025_auto_20210201_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solution_text',
            field=models.TextField(default='(soluzione non ancora inserita)'),
        ),
        migrations.CreateModel(
            name='MacroQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_text', models.TextField()),
                ('text', models.TextField(default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.course')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elearningapp.macroquestion'),
        ),
    ]
