# Generated by Django 3.1.4 on 2021-02-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0026_auto_20210201_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroquestion',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elearningapp.category'),
        ),
    ]
