# Generated by Django 3.1.4 on 2021-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0027_macroquestion_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macroquestion',
            name='rendered_text',
            field=models.TextField(default=''),
        ),
    ]
