# Generated by Django 3.1.4 on 2021-02-01 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0031_auto_20210201_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='seenquestion',
            name='macro_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='elearningapp.macroquestion'),
        ),
        migrations.AlterField(
            model_name='seenquestion',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='elearningapp.question'),
        ),
    ]
