# Generated by Django 3.1.4 on 2021-02-01 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elearningapp', '0032_auto_20210201_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activequestion',
            name='macro_question',
        ),
        migrations.RemoveField(
            model_name='seenquestion',
            name='macro_question',
        ),
        migrations.AlterField(
            model_name='seenquestion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearningapp.question'),
        ),
        migrations.CreateModel(
            name='SeenMacroQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('macro_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.macroquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
