# Generated by Django 3.1.4 on 2021-02-01 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0033_auto_20210201_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMacroQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='elearningapp.macroquestion')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.activetest')),
            ],
        ),
    ]
