# Generated by Django 3.1.4 on 2021-02-02 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elearningapp', '0035_auto_20210201_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exercise_modality',
        ),
        migrations.AddField(
            model_name='activetest',
            name='questions',
            field=models.ManyToManyField(to='elearningapp.Question'),
        ),
        migrations.AlterField(
            model_name='globalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ActiveQuestion',
        ),
    ]
