# Generated by Django 3.1.4 on 2021-02-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0036_auto_20210202_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category_distribution',
        ),
        migrations.RemoveField(
            model_name='question',
            name='edits_history',
        ),
        migrations.RemoveField(
            model_name='question',
            name='number_of_appearences',
        ),
        migrations.RemoveField(
            model_name='question',
            name='number_of_selections_per_answer',
        ),
        migrations.AddField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='uses_category_distribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elearningapp.category'),
        ),
    ]
