# Generated by Django 3.1.4 on 2021-02-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0038_auto_20210202_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='quantity',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='minimum_passing_testcase_perc',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='CourseSpecificProfile',
        ),
        migrations.DeleteModel(
            name='GlobalProfile',
        ),
    ]
