# Generated by Django 3.1.4 on 2021-02-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0039_auto_20210203_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selections',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='number_of_appearances',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
