# Generated by Django 3.1.4 on 2021-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0040_auto_20210203_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='percentage_of_correct_answers',
            field=models.FloatField(default=100.0),
        ),
    ]
