# Generated by Django 3.1.4 on 2021-02-04 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elearningapp', '0041_question_percentage_of_correct_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('C', 'Create'), ('E', 'Edit')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
