# Generated by Django 3.1.4 on 2021-02-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0042_staffaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaction',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
