# Generated by Django 3.1.4 on 2021-02-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210207_1337'),
        ('elearningapp', '0044_coursepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepermission',
            name='course',
        ),
        migrations.AlterField(
            model_name='coursepermission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.coursespecificprofile'),
        ),
    ]
