# Generated by Django 3.1.4 on 2021-02-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0045_auto_20210207_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepermission',
            old_name='can_add_contributors',
            new_name='can_manage_contributors',
        ),
        migrations.RemoveField(
            model_name='coursepermission',
            name='can_edit_contributors',
        ),
    ]
