# Generated by Django 3.1.6 on 2021-02-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearningapp', '0048_report_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearningapp.question'),
        ),
    ]
